### ISSUE TITLE
[Task] DB schema를 참조하여 Entity 클래스 구성하기

### ISSUE THREAD

**Issue by nmin11** [codestates/Project_TT#26]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: Spring의 @Entity 어노테이션을 활용하여 DB의 컬럼과 Java의 객체 연결

### TODO
1. [x] user entity 생성
2. [x] review board entity 생성
3. [x] comment entity 생성
4. [x] review board와 hash tag N:M 연결

### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Urgency: `Middle`
