### ISSUE TITLE
2021. 10. 06 To-Do-List

### ISSUE THREAD

**Issue by nmin11** [codestates/Project_TT#4]
### TODO
1. [x] 기능 To Do List
2. [x] 스키마 작성
3. [x] API 문서 작성
4. [x] 아키텍처 다이어그램 작성
5. [x] Work log, Team Role 작성
6. [x] KPT 작성
