### ISSUE TITLE
[Task] Review, Comment CRUD 구현 및 작동 확인

### ISSUE THREAD

**Issue by nmin11** [codestates/Project_TT#53]
### ISSUE
- Group:  `server`
- Type: `feature`
- Back-End 리뷰 및 댓글 CRUD 로직 작성 및 작동 확인

### TODO
1. [x] Review CRUD 로직 구현
2. [x] Review CRUD 로직 작동 확인
3. [x] Comment CRUD 로직 구현
4. [x] Comment CRUD 로직 작동 확인

### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Urgency: `High`
