### ISSUE TITLE
[Task] 추가해야 할 API 메소드들 구현하기

### ISSUE THREAD

**Issue by nmin11** [codestates/Project_TT#56]
### ISSUE
- Group:  `server`
- Type: `feature`, 'fix'
- Detail1: 아직 구현하지 못한 세부 메소드들 구현 필요
- Detail2: 회의를 통해 제대로 구현되지 못한 로직이 제보되어 수정 필요

### TODO
1. [x] 로그인 기능 : email만 맞아도 로그인이 되는 문제 해결해야 함
2. [x] 이메일 중복과 닉네임 중복 get 요청을 따로 빼야 함
3. [x] 회원 정보 수정 로직 구현해야 함
4. [x] 마이 페이지 접속 시, 토큰 유효성 검사 로직
5. [x] 마이 페이지에서 내가 쓴 리뷰를 볼 수 있도록 따로 get 메소드 생성해야 함
6. [x] 테마별 여행 : 리뷰를 테마별로 조회하는 기능도 있어야 함

### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Urgency: `High`
